Repository shinhanDsActeam/AirBnG, pull requests merged in 2025-07, with the labels that each got.

#36 [#55] feat : 내 정보 수정
  src/main/java/com/airbng/common/response/status/BaseResponseStatus.java
  src/main/java/com/airbng/controller/MemberController.java
  src/main/java/com/airbng/dto/MemberUpdateRequest.java
  src/main/java/com/airbng/mappers/ImageMapper.java
  src/main/java/com/airbng/mappers/MemberMapper.java
  src/main/java/com/airbng/service/ImageService.java
  src/main/java/com/airbng/service/ImageServiceImpl.java
  src/main/java/com/airbng/service/MemberService.java
  src/main/java/com/airbng/service/MemberServiceImpl.java
  src/main/resources/mappers/ImageMapper.xml
  src/main/resources/mappers/MemberMapper.xml
  src/test/java/com/airbng/service/MemberServiceTest.java
Labels: ✨ 기능

#42 [#57] feat : 로그인 화면 만들기
  src/main/java/com/airbng/controller/MemberController.java
  src/main/java/com/airbng/controller/MemberPageController.java
  src/main/webapp/WEB-INF/views/login.jsp
  src/main/webapp/css/login.css
  src/main/webapp/js/login.js
Labels: 🎨 디자인

#41 [#77] feat : 예약 상세 화면 만들기
  src/main/java/com/airbng/controller/ReservationPageController.java
  src/main/webapp/WEB-INF/views/reservationDetails.jsp
  src/main/webapp/css/navigation.css
  src/main/webapp/css/reservationDetails.css
  src/main/webapp/images/calendar.svg
  src/main/webapp/images/home.svg
  src/main/webapp/images/messages.svg
  src/main/webapp/images/shopping-cart.svg
  src/main/webapp/images/user.svg
  src/main/webapp/js/reservationDetails.js
Labels: 🎨 디자인

#48 [# 76] fe 검색 페이지 만들기
  src/main/java/com/airbng/controller/LockerPageController.java
  src/main/webapp/WEB-INF/views/search.jsp
  src/main/webapp/css/bottom-sheet.css
  src/main/webapp/css/search.css
  src/main/webapp/images/Group 2.svg
  src/main/webapp/images/arrow-left.svg
  src/main/webapp/js/search.js
Labels: 🎨 디자인

#51 [#89] 예약 내역 삭제
  src/main/java/com/airbng/common/response/status/BaseResponseStatus.java
  src/main/java/com/airbng/controller/ReservationController.java
  src/main/java/com/airbng/mappers/ReservationMapper.java
  src/main/java/com/airbng/service/ReservationService.java
  src/main/java/com/airbng/service/ReservationServiceImpl.java
  src/main/resources/mappers/ReservationMapper.xml
  src/main/webapp/WEB-INF/views/ReservationList.jsp
  src/main/webapp/css/ReservationList.css
  src/main/webapp/js/ReservationList.js
Labels: 🎨 디자인, ✨ 기능

#54 [# 81] fe 보관소 상세 화면 만들기
  src/main/java/com/airbng/controller/LockerPageController.java
  src/main/java/com/airbng/dto/locker/LockerDetailResponse.java
  src/main/resources/mappers/LockerMapper.xml
  src/main/webapp/WEB-INF/views/lockerDetails.jsp
  src/main/webapp/WEB-INF/views/splash.jsp
  src/main/webapp/css/lockerDetails.css
  src/main/webapp/js/lockerDetails.js
Labels: 🎨 디자인, ✨ 기능

#33 [#62] feat : 미확정시 알람 발생 기능 개발
  pom.xml
  src/main/java/com/airbng/common/response/status/BaseResponseStatus.java
  src/main/java/com/airbng/config/RedisConfig.java
  src/main/java/com/airbng/config/WebAppInitializer.java
  src/main/java/com/airbng/config/WebConfig.java
  src/main/java/com/airbng/controller/AlarmPageTestController.java
  src/main/java/com/airbng/controller/ReservationAlarmSseController.java
  src/main/java/com/airbng/controller/SchedulerManualTriggerController.java
  src/main/java/com/airbng/domain/base/NotificationType.java
  src/main/java/com/airbng/domain/base/ReservationState.java
  src/main/java/com/airbng/dto/AlarmResponse.java
  src/main/java/com/airbng/dto/reservation/ReservationResponse.java
  src/main/java/com/airbng/mappers/ReservationMapper.java
  src/main/java/com/airbng/scheduler/AlertScheduledTask.java
  src/main/java/com/airbng/service/ReservationAlarmCacheService.java
  src/main/java/com/airbng/service/ReservationAlarmCacheServiceImpl.java
  src/main/java/com/airbng/service/ReservationAlarmSseService.java
  src/main/java/com/airbng/service/ReservationAlarmSseServiceImpl.java
  src/main/resources/mappers/ReservationMapper.xml
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/alarm.html
Labels: ✨ 기능

#53 [#78] 맡기기 화면 구현하기
  src/main/java/com/airbng/common/exception_handler/FieldValidationControllerAdvice.java
  src/main/java/com/airbng/controller/HomePageController.java
  src/main/java/com/airbng/controller/ReservationPageController.java
  src/main/java/com/airbng/mappers/LockerMapper.java
  src/main/java/com/airbng/service/ReservationServiceImpl.java
  src/main/resources/mappers/LockerMapper.xml
  src/main/webapp/WEB-INF/views/common/modal.jsp
  src/main/webapp/WEB-INF/views/example.js
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/navbar.jsp
  src/main/webapp/WEB-INF/views/reservationForm.jsp
  src/main/webapp/css/common/modal.css
  src/main/webapp/css/reservationForm.css
  src/main/webapp/js/common/modal.js
  src/main/webapp/js/home.js
  src/main/webapp/js/reservationForm.js
  src/test/java/com/airbng/service/ReservationServiceTest.java
Labels: 🎨 디자인, ✨ 기능
